version: '3.8'

services:

  discovery:
    image: zanzadshubham25/medisync-discovery:latest
    container_name: medisync-discovery
    ports:
      - "8761:8761"
    restart: unless-stopped

  gateway:
    image: zanzadshubham25/medisync-gateway:latest
    container_name: medisync-gateway
    ports:
      - "9005:9005"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - discovery
    restart: unless-stopped

  account:
    image: zanzadshubham25/medisync-account:latest
    container_name: medisync-account
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - ABDM_URL=http://abdm:9009
    depends_on:
      - gateway
    restart: unless-stopped

  patient:
    image: zanzadshubham25/medisync-patient:latest
    container_name: medisync-patient
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - ABDM_URL=http://abdm:9009
    depends_on:
      - gateway
    restart: unless-stopped

  consent:
    image: zanzadshubham25/medisync-consent:latest
    container_name: medisync-consent
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - ABDM_URL=http://abdm:9009
    depends_on:
      - gateway
    restart: unless-stopped

  abdm:
    image: zanzadshubham25/medisync-abdm:latest
    container_name: medisync-abdm
    ports:
      - "9009:9009"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    depends_on:
      - gateway
    restart: unless-stopped

  frontend:
    image: zanzadshubham25/medisync-frontend:latest
    container_name: medisync-frontend
    ports:
      - "80:80"
    depends_on:
      - gateway
    restart: unless-stopped
