spring.application.name=consent-service
server.port=0
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.file.name = appLog.log
logging.pattern.file=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.client.enabled=false

# RabbitMQ setup
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}

exchange.name=abdm
queue.name=IN2210000259-consent-queue
routingKey.name=IN2210000259-consent
#queue.name=IN2210000259-consent-queue
#routingKey.name=IN2210000259-consent
#
#hospital.Id=IN1910000503

hospital.name=Fledlucifers Eye care Hospital
hospital.Id=IN2210000259


#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

ngrok.uri=https://webhook.site/e7dfa3bd-5c38-482d-8bed-3fd81ccedb4b

abdm.url=${ABDM_URL}

# DB encryption key
database.encryption.key=${DATABASE_ENCRYPTION_KEY}
